version: '3'
services:
  node-service:
    build: .
    container_name: node-service
    restart: always
    networks:
      - node-network

  mongo:
    image: mongo:latest 
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - node-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
      # - "80:80"
      # - "443:443"
    networks: 
      - node-network




networks:
  node-network:
    driver: bridge
